}
     catch(const char* txtException) {
         cout <<"Exception: "<< txtException << endl;
     }
     catch(int exCode) {
        cout <<"Exception: "<< exCode << endl;
     }